server:
  port: 8090
  # MySQL Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/students
    username: root
    password: Jerry@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

# Eureka Client Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
